name: ClamAV Scan

on:
  push:
    branches:
      - master

jobs:
  clamav:
    runs-on: ubuntu-latest
    steps:
      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav
      - name: Scan Repository
        run: clamscan -r --exclude-dir=.git ./
