on: [push]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: Last Commit AV Scan
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: Git AV Scan
        uses: djdefi/gitavscan@main
        with:
          sha: ${{ github.sha }}
