name: ClamAV Scan

on:
  push:
    branches:
      - main

jobs:
  clamav:
    runs-on: ubuntu-latest
    steps:
      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav
      - name: Stop ClamAV Daemon
        run: |
          sudo systemctl stop clamav-daemon
      - name: Update ClamAV Database
        run: |
          sudo freshclam --datadir=/var/lib/clamav
      - name: Scan Repository
        run: clamscan -r --exclude-dir=.git ./
      - name: Start ClamAV Daemon
        run: |
          sudo systemctl start clamav-daemon
